apiVersion: apps/v1
kind: Deployment
metadata:
  name: loop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loop
  template:
    metadata:
      labels:
        app: loop
    spec:
      initContainers:
      - image: okteto/hello-world:golang
        name: i1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      containers:
      - image: okteto/hello-world:golang
        name: c1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
