apiVersion: apps/v1
kind: Deployment
metadata:
  name: private
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private
  template:
    metadata:
      labels:
        app: private
    spec:
      containers:
      - image: okteto/private-nginx
        name: c1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
