apiVersion: apps/v1
kind: Deployment
metadata:
  name: psp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: psp
  template:
    metadata:
      labels:
        app: psp
    spec:
      containers:
      - image: okteto/hello-world:golang
        name: c1
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
