apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quota
  template:
    metadata:
      labels:
        app: quota
    spec:
      containers:
      - image: okteto/hello-world:golang
        name: c1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "12Gi"
            cpu: "100m"
